// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9pnpzwiqk7SDDJEsNqd4iaCt76MVWTW0',
    appId: '1:1063685137532:android:532e7237825e6ff90515f9',
    messagingSenderId: '1063685137532',
    projectId: 'baby-journal-29fc3',
    storageBucket: 'baby-journal-29fc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgYrEXX0r6ZbjkslS4TpTjMO4SYy5Opw4',
    appId: '1:1063685137532:ios:283c16eb8280ff4a0515f9',
    messagingSenderId: '1063685137532',
    projectId: 'baby-journal-29fc3',
    storageBucket: 'baby-journal-29fc3.appspot.com',
    androidClientId: '1063685137532-53grjpuqorfmk7i7bbh8i5eb6a6e9fnv.apps.googleusercontent.com',
    iosClientId: '1063685137532-lbi46561qt0vngesjres5jcvpf6514av.apps.googleusercontent.com',
    iosBundleId: 'com.example.babyJournal',
  );
}
